In [23]:
import numpy as np


In [24]:
#creating a numpy array of length 14
a = np.arange(14)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [25]:
# reshaping one dimensional array to two dimensional
a.reshape(2,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [26]:
#resizeing an numpy array to another shape
resized_array = np.resize(a,(3,6))
resized_array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13,  0,  1,  2,  3]])

In [27]:
# numpy dot
np2 = np.array([1,2,3,4,5,6])
output_np = resized_array.dot(np2)

In [28]:
output_np


array([ 70, 196,  70])

In [29]:
np.matmul(resized_array,np2)

array([ 70, 196,  70])

In [30]:
# Python program explaining 
# where() function 

import numpy as np 

# a is an array of integers. 
a = np.array([[1, 2, 3], [4, 5, 6]]) 

print(a) 

print ('Indices of elements <4') 

b = np.where(a>2) 
print(b) 

print("Elements which are <4") 
print(a[b]) 


[[1 2 3]
 [4 5 6]]
Indices of elements <4
(array([0, 1, 1, 1]), array([2, 0, 1, 2]))
Elements which are <4
[3 4 5 6]


In [31]:
np.where(resized_array>1)

(array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2]),
 array([2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 4, 5]))

In [32]:
resized_array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13,  0,  1,  2,  3]])

In [33]:
np2

array([1, 2, 3, 4, 5, 6])

In [34]:
#indexing
resized_array[2,4]

2

In [35]:
resized_array[0,5]

5

In [36]:
# slicing
resized_array[2,0:3]

array([12, 13,  0])

In [37]:
resized_array[0,3:6:2]

array([3, 5])

In [38]:
#mean
np.mean(resized_array)

5.388888888888889

In [39]:
#row wise mean
np.mean(resized_array,axis=1)

array([2.5       , 8.5       , 5.16666667])

In [40]:
#column wise mean
np.mean(resized_array,axis=0)

array([6.        , 7.        , 3.33333333, 4.33333333, 5.33333333,
       6.33333333])

In [41]:
#median
np.median(resized_array)

4.5

In [42]:
#row wise median
np.median(resized_array,axis=1)

array([2.5, 8.5, 2.5])

In [43]:
#column wise median
np.median(resized_array,axis=0)

array([6., 7., 2., 3., 4., 5.])

In [44]:
#mode 
from scipy import stats
a =stats.mode(resized_array)

In [45]:
a

ModeResult(mode=array([[0, 1, 0, 1, 2, 3]]), count=array([[1, 1, 1, 1, 1, 1]]))

In [46]:
# standard deaviation
np.std(resized_array)

4.151825420340751

In [47]:
#row wise standard deviation
np.std(resized_array,axis =1)

array([1.70782513, 1.70782513, 5.27309734])

In [48]:
#column wise standard deviation
np.std(resized_array,axis =0)

array([4.89897949, 4.89897949, 3.39934634, 3.39934634, 3.39934634,
       3.39934634])

In [49]:
resized_array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13,  0,  1,  2,  3]])

In [50]:
#average
np.average(resized_array)

5.388888888888889

In [51]:
#average column wise
np.average(resized_array,axis=0)

array([6.        , 7.        , 3.33333333, 4.33333333, 5.33333333,
       6.33333333])

In [52]:
#average row wise
np.average(resized_array,axis=1)

array([2.5       , 8.5       , 5.16666667])

In [53]:
resized_array


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13,  0,  1,  2,  3]])

In [54]:
# transpose 
np.transpose(resized_array)

array([[ 0,  6, 12],
       [ 1,  7, 13],
       [ 2,  8,  0],
       [ 3,  9,  1],
       [ 4, 10,  2],
       [ 5, 11,  3]])

In [55]:
a=np.array([[1,2,3],[2,3,4]])

In [56]:
b = np.array([9,9,9])

In [57]:
a+b

array([[10, 11, 12],
       [11, 12, 13]])

In [58]:
import numpy as np

In [59]:
#add in numpy
np.add(1.0, 4.0)

x1 = np.arange(12.0).reshape((3, 4))
x2 = np.arange(4.0)
np.add(x1, x2)

array([[ 0.,  2.,  4.,  6.],
       [ 4.,  6.,  8., 10.],
       [ 8., 10., 12., 14.]])

In [60]:
x1

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [61]:
x2

array([0., 1., 2., 3.])

In [62]:
np.add(x1,x2)

array([[ 0.,  2.,  4.,  6.],
       [ 4.,  6.,  8., 10.],
       [ 8., 10., 12., 14.]])

In [63]:
#numpy sum 
np.sum(x1,axis=0)

array([12., 15., 18., 21.])

In [64]:
#numpy transpose
np.transpose(x1)

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [65]:
x1

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [75]:
#numpy multiply
np.multiply(x1,x2)

array([[ 0.,  1.,  4.,  9.],
       [ 0.,  5., 12., 21.],
       [ 0.,  9., 20., 33.]])

In [76]:
x1 = np.arange(12.0).reshape((3, 4))
x2 = np.arange(4.0).reshape((1,4))

In [77]:
np.multiply(x1,x2)

array([[ 0.,  1.,  4.,  9.],
       [ 0.,  5., 12., 21.],
       [ 0.,  9., 20., 33.]])

In [78]:
x1

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [80]:
x2

array([[0., 1., 2., 3.]])

In [85]:
# inverse in numpy
xx = np.arange(4).reshape((2,2))
xx
np.linalg.inv(xx) 

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [93]:
i = np.array([[1,1,1],[0,2,5],[2,5,1]])
i2= np.arange(9).reshape((3,3))
i


array([[1, 1, 1],
       [0, 2, 5],
       [2, 5, 1]])

In [92]:
np.linalg.inv(i)

array([[ 1.35294118, -0.23529412, -0.17647059],
       [-0.58823529,  0.05882353,  0.29411765],
       [ 0.23529412,  0.17647059, -0.11764706]])

In [94]:
i2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [95]:
np.linalg.inv(i2)

LinAlgError: Singular matrix

In [96]:
np.invert(i2)

array([[-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]])

In [104]:
#random module in numpy
# randint returns array with givel size and each element is lower than the first parameter
np.random.randint(12, size=10)

array([4, 0, 0, 0, 8, 7, 2, 6, 0, 4])

In [105]:
np.random.rand(10)

array([0.76084091, 0.90361055, 0.91707585, 0.13787849, 0.54461471,
       0.04480037, 0.61294828, 0.50163705, 0.93155891, 0.37123746])

In [100]:
np.random.randn(10)

array([-0.79522731, -0.58447944, -0.27954763, -1.39416323,  1.05050037,
        2.70621084,  0.96641304,  0.11327879,  0.71436128, -0.47232681])

In [106]:
np.random.random_integers(5)


/home/ganesh/venv/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  """Entry point for launching an IPython kernel.


2

In [107]:
np.random.random_sample()

0.5654938088737713

In [108]:
np.random.random_sample(5)

array([0.94730719, 0.87518738, 0.96626186, 0.18853312, 0.86103355])

In [114]:
np.random.random_sample((3,2)) - 77

array([[-76.1951197 , -76.43419771],
       [-76.32446384, -76.96004959],
       [-76.19509442, -76.94161944]])

In [118]:
np.random.ranf(6).reshape((2,3))

array([[0.45464459, 0.67634151, 0.53469392],
       [0.00389986, 0.55244676, 0.20899691]])

In [119]:
np.random.ranf(6)

array([0.66064964, 0.78388805, 0.78622478, 0.10163745, 0.76161616,
       0.84562105])

In [120]:
np.random.sample(6)

array([0.84469816, 0.88112165, 0.38363661, 0.29402496, 0.50802321,
       0.53333539])