In [1]:
import numpy as np


In [7]:
#creating a numpy array of length 14
a = np.arange(14)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [8]:
# reshaping one dimensional array to two dimensional
a.reshape(2,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [11]:
#resizeing an numpy array to another shape
resized_array = np.resize(a,(3,6))
resized_array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13,  0,  1,  2,  3]])

In [38]:
# numpy dot
np2 = np.array([1,2,3,4,5,6])
output_np = resized_array.dot(np2)

In [39]:
output_np


array([ 70, 196,  70])

In [40]:
np.matmul(resized_array,np2)

array([ 70, 196,  70])

In [41]:
# Python program explaining 
# where() function 

import numpy as np 

# a is an array of integers. 
a = np.array([[1, 2, 3], [4, 5, 6]]) 

print(a) 

print ('Indices of elements <4') 

b = np.where(a>2) 
print(b) 

print("Elements which are <4") 
print(a[b]) 


[[1 2 3]
 [4 5 6]]
Indices of elements <4
(array([0, 1, 1, 1]), array([2, 0, 1, 2]))
Elements which are <4
[3 4 5 6]


In [47]:
np.where(resized_array>1)

(array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2]),
 array([2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 4, 5]))

In [23]:
resized_array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13,  0,  1,  2,  3]])

In [44]:
np2

array([1, 2, 3, 4, 5, 6])

In [48]:
#indexing
resized_array[2,4]

2

In [49]:
resized_array[0,5]

5

In [50]:
# slicing
resized_array[2,0:3]

array([12, 13,  0])

In [53]:
resized_array[0,3:6:2]

array([3, 5])

In [54]:
#mean
np.mean(resized_array)

5.388888888888889

In [55]:
#row wise mean
np.mean(resized_array,axis=1)

array([2.5       , 8.5       , 5.16666667])

In [56]:
#column wise mean
np.mean(resized_array,axis=0)

array([6.        , 7.        , 3.33333333, 4.33333333, 5.33333333,
       6.33333333])

In [57]:
#median
np.median(resized_array)

4.5

In [58]:
#row wise median
np.median(resized_array,axis=1)

array([2.5, 8.5, 2.5])

In [59]:
#column wise median
np.median(resized_array,axis=0)

array([6., 7., 2., 3., 4., 5.])

In [61]:
#mode 
from scipy import stats
stats.mode(resized_array)

ModuleNotFoundError: No module named 'scipy'